version: 2

orbs:
  coveralls: coveralls/coveralls@1.0.4

jobs:
  lint:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.30.0
      - run: golangci-lint --exclude-use-default=false run ./...

  test:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: GO111MODULE=off go get github.com/mattn/goveralls
      - run: go test -v -cover -race -coverprofile=/home/circleci/test/coverage.out
      - run: $GOPATH/bin/goveralls -coverprofile=/home/circleci/test/coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN

workflows:
  version: 2
  test:
    jobs:
      - lint
      - test:
          requires:
            - lint
